name: GitHub Actions Demo
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
        - name: install modules
          run: : npm install
        - name: build project
          run: npm run build
        - name: e2e test
          run: npm run test:e2e

